{% macro get_sdm_partition_columns() %}
event_timestamp_year,event_timestamp_month,event_timestamp_day,event_timestamp_hour,parsed_interval_timestamp_year,parsed_interval_timestamp_month,parsed_interval_timestamp_day,parsed_interval_timestamp_hour
{% endmacro %}